// src/components/ScreenTab.vue
<script setup lang="ts">
import LayoutPanel from "./LayoutPanel.vue";
import PropertiesPanel from "./PropertiesPanel.vue";
import BlocksPanel from "./BlocksPanel.vue";
import Splitter from "primevue/splitter";
import SplitterPanel from "primevue/splitterpanel";
import { ref } from "vue";
import { AIScreen } from "aia-kit/ai_screen.js";
import { AIComponent } from "aia-kit/ai_component.js";

let props = defineProps<{ screen: AIScreen }>();

const screen = props.screen;

let selectedComponent = ref(screen.form);

function onComponentSelected(component: AIComponent) {
    selectedComponent.value = component;
}

</script>

<template>
    <Splitter>
        <SplitterPanel :minSize="20">
            <LayoutPanel :form="screen.form" @componentSelected="onComponentSelected" />
        </SplitterPanel>
        <SplitterPanel :minSize="20">
            <PropertiesPanel :component="selectedComponent" />
        </SplitterPanel>
        <SplitterPanel :minSize="30">
            <BlocksPanel :blocksXml="screen.blocks" />
        </SplitterPanel>
    </Splitter>
</template>

// src/components/ScreenTab.tsx
import {AIScreen} from "aia-kit/dist/ai_screen";
import React, {useState} from "react";
import {Container, Grid} from "@mantine/core";
import {LayoutPanel} from "./LayoutPanel";
import {PropertiesPanel} from "./PropertiesPanel";
import {BlocksPanel} from "./BlocksPanel";

export function ScreenTab({screen}: { screen: AIScreen }) {
    const [selected, setSelected] = useState(screen.form)
    return (
        <Container fluid>
            <Grid>
                <Grid.Col span={3}>
                    <LayoutPanel form={screen.form} selected={selected} setSelected={setSelected}/>
                </Grid.Col>
                <Grid.Col span={3}>
                    <PropertiesPanel component={selected}/>
                </Grid.Col>
                <Grid.Col span={6}>
                    <BlocksPanel blocksXml={screen.blocks}/>
                </Grid.Col>
            </Grid>
        </Container>
    )
}
