// src/Explorer.tsx
import {Center, Indicator, Loader, Tabs} from '@mantine/core';
import React from "react";
import {useQuery} from "@tanstack/react-query";
import {AIAReader} from "./unchive/aia_reader";
import {IconDeviceMobile, IconIcons, IconPuzzle} from "@tabler/icons-react";
import {ScreenTab} from "./components/ScreenTab";
import {ExtensionsTab} from "./components/ExtensionsTab";
import {AssetsTab} from "./components/AssetsTab";
import {OverviewTab} from "./components/OverviewTab";

export function Explorer({file}: { file: File }) {

    const {isLoading, isError, data: project} = useQuery({
        queryKey: ['aia'],
        queryFn: () => AIAReader.read(file)
    })

    if (isError) {
        return <p>error</p>
    }

    if (isLoading) {
        return <Center style={{height: "100%"}}><Loader/></Center>
    }

    return (
        <Tabs defaultValue="overview" keepMounted={false}>
            <Tabs.List>
                <Tabs.Tab value="overview"><b>{project.name}</b></Tabs.Tab>
                <Indicator label={project.assets.length} inline size={16}>
                    <Tabs.Tab value="assets" icon={<IconIcons/>}>Assets</Tabs.Tab>
                </Indicator>
                <Indicator label={project.extensions.length} inline size={16}>
                    <Tabs.Tab value="extensions" icon={<IconPuzzle/>}>Extensions</Tabs.Tab>
                </Indicator>
                {
                    project.screens.map((screen) => (
                        <Tabs.Tab key={screen.name} value={screen.name}
                                  icon={<IconDeviceMobile/>}>{screen.name}</Tabs.Tab>
                    ))
                }
            </Tabs.List>
            <Tabs.Panel value="overview">
                <OverviewTab project={project}/>
            </Tabs.Panel>
            <Tabs.Panel value="assets">
                <AssetsTab assets={project.assets}/>
            </Tabs.Panel>
            <Tabs.Panel value="extensions">
                <ExtensionsTab exts={project.extensions}/>
            </Tabs.Panel>
            {
                project.screens.map((screen) => (
                    <Tabs.Panel key={screen.name} value={screen.name}>
                        <ScreenTab screen={screen}/>
                    </Tabs.Panel>
                ))
            }
        </Tabs>
    )
}

// src/Explorer.vue
<script setup lang="ts">
import PanelMenu from 'primevue/panelmenu';
import Splitter from 'primevue/splitter';
import SplitterPanel from 'primevue/splitterpanel';
import { IconDeviceMobile, IconIcons, IconPuzzle } from "@tabler/icons-react";
import ScreenTab from "./components/ScreenTab.vue";
import ExtensionsTab from "./components/ExtensionsTab.vue";
import AssetsTab from "./components/AssetsTab.vue";
import OverviewTab from "./components/OverviewTab.vue";

import { computed, ref } from 'vue';
import { AIProject } from "aia-kit/ai_project.js";

let props = defineProps<{ project: AIProject }>();

const project = props.project;

let activeTab = ref('overview');
let selectedScreen = ref(null);

const items = computed(() => [
    {
        label: 'Project',
        command: () => {
            activeTab.value = 'overview';
        },
    },
    {
        label: 'Assets',
        command: () => {
            activeTab.value = 'assets';
        },
    },
    {
        label: 'Extensions',
        command: () => {
            activeTab.value = 'extensions';
        },
    },
    {
        label: 'Screens',
        items: project.screens.map((screen) => ({
            label: screen.name,
            command: () => {
                selectedScreen.value = screen;
                activeTab.value = 'screen';
            },
        })),
    }
]);

</script>

<template>
    <Splitter>
        <SplitterPanel :size="15" :minSize="15">
            <PanelMenu :model="items" />
        </SplitterPanel>
        <SplitterPanel :size="85">
            <div v-if="activeTab === 'overview'">
                <OverviewTab :project="project" />
            </div>
            <div v-else-if="activeTab === 'assets'">
                <AssetsTab :assets="project.assets" />
            </div>
            <div v-else-if="activeTab === 'extensions'">
                <ExtensionsTab :exts="project.extensions" />
            </div>
            <div v-else-if="activeTab === 'screen'">
                <ScreenTab :screen="selectedScreen" />
            </div>
        </SplitterPanel>
    </Splitter>
</template>
